apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`guacamole.dev.vogelfamily.ch`)
      kind: Rule
      middlewares:
        - name: guacamole-header
        - name: guacamole-regex      
      services:
        - name: guacamole-svc
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`guacamole.dev.vogelfamily.ch`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: traefik
      services:
        - name: guacamole-svc
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: guacamole-header
spec:
  headers:
    accessControlAllowOriginList:
      - "https://guacamole.dev.vogelfamily.ch"
          