apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole-tls
  namespace: guacamole  
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`guacamole.vogelfamily.ch`)
      kind: Rule
      middlewares:
        - name: guacamole-header
        - name: guacamole-regex      
      services:
        - name: guacamole-svc
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole
  namespace: guacamole
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`guacamole.vogelfamily.ch`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: traefik
      services:
        - name: guacamole-svc
          port: 8080
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
  # name: redirect-https
  # namespace: guacamole  
# spec:
  # redirectScheme:
    # scheme: https
    # permanent: true   
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: guacamole-header
  namespace: guacamole  
spec:
  headers:
    forceSTSHeader: true
    stsPreload: true
    contentTypeNosniff: true
    browserXssFilter: true
    stsIncludeSubdomains: true
    stsSeconds: 63072000
    frameDeny: true
    sslRedirect: true
    accessControlAllowMethods:
      - "GET"
    accessControlAllowOriginList:
      - "https://guacamole.dev.vogelfamily.ch"
    accessControlMaxAge: 100
    addVaryHeader: true
    customFrameOptionsValue: SAMEORIGIN
    hostsProxyHeaders:
    - "X-Forwarded-Host"
    referrerPolicy: "same-origin"    
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: guacamole-regex
  namespace: guacamole  
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(?:card|cal)dav"
    replacement: "https://${1}/remote.php/dav"      