apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  selector:
    matchLabels:
      run: guacd
  replicas: 1
  template:
    metadata:
      labels:
        run: guacd
    spec:
      containers:
      - name: guacd
        image: guacamole/guacd:1.5.5
        ports:
        - containerPort: 4822
