apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guacamole
  
resources:
- guacamole-ns.yaml
- guacd-svc.yaml
- guacd-dpl.yaml
- guacamole-cm.yaml
- guacamole-svc.yaml
- guacamole-dpl.yaml
- gucamole-ir.yaml
